version: 0.0
os: linux
env: 
  parameter-store:
    SOURCE: /index.html
    DESTINATION: /var/www/html/
files:
  - source: $SOURCE
    destination: $DESTINATION
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
